framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
        excluded_patterns:
            # Exclure les partials SCSS (fichiers commençant par _)
            - '**/assets/styles/**/_*.scss'
            # Exclure tout le dossier Bootstrap SCSS
            - '**/assets/vendor/bootstrap/scss/**'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
